NUMPY - Numerical Python

In [4]:
import numpy as np

In [5]:
arr = np.array([])  # creating an empty array
arr

array([], dtype=float64)

In [6]:
#list to numpy array 
l=[]
a=np.array(l)
type(a)

numpy.ndarray

In [7]:
l=[3,'s',5.8,True,7+9j]
a=np.array(l)
print(type(a))
print(a.dtype)       #it is giving datatype

<class 'numpy.ndarray'>
<U64


In [10]:
l=[3,5.8,True]
a=np.array(l)
print(type(a))
print(a.dtype)

<class 'numpy.ndarray'>
float64


In [11]:
l=[3,8,True]
a=np.array(l)
print(type(a))
print(a.dtype)

<class 'numpy.ndarray'>
int64


-- Properties of numpy

Homogenous -- all elements should be same data type.

Fixed Size - Once created the array size cannot change.

Mutable -- Values can be modified after creation.

In [7]:
d = np.array([100,200,300,400])
print(d)

[100 200 300 400]


In [10]:
id(d)

2027188034352

In [9]:
d=np.append(d,[500,600])
d

array([100, 200, 300, 400, 500, 600])

In [11]:
id(d)

2027188034352

In [16]:
a=np.array([[1,4,6]])
a.ndim     #ndim it gives number of dimensions =no of square braces

2

In [15]:
a=np.array([[[[[1,4,6]]]]])
a.ndim     

5

In [21]:
a=np.array([[[[[1,4,5,6]]]]])
a.size    #it gives no of elements    

4

In [32]:
a.shape     #it gives no of rows and columns

(1, 1, 1, 1, 4)

In [19]:
a=np.array([[1,4,5,6,8,9]])
a.size    #it gives no of elements    

6

In [20]:
a.shape

(1, 6)

In [31]:
b=np.array([[1,2,5,4],[5,6,7,7],[2,3,4,5]])
print(b)
print(b.ndim)
print(type(b))
print(b.dtype)
print(b.size)
print(b.shape)

[[1 2 5 4]
 [5 6 7 7]
 [2 3 4 5]]
2
<class 'numpy.ndarray'>
int64
12
(3, 4)


In [66]:
arr1=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr1)
print(arr1.ndim)
print(arr1.shape)          #it gives output as 2,2,3 because it has 2 blocks then in each block it has 2 rows and 3 columns
print(arr1.size)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3
(2, 2, 3)
12


In [20]:
arr1 = np.arange(10,100,5)
arr1

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [21]:
len(arr1)

18

In [22]:
arr1[4]

np.int64(30)

In [23]:
arr1[-4]

np.int64(80)

In [24]:
arr1[4:9:3]

array([30, 45])

In [72]:
print(arr1[1:,::,::2])

[[[ 7  9]
  [10 12]]]


In [75]:
print(arr1[0:1,::,::2])

[[[1 3]
  [4 6]]]


In [55]:
arr1=np.array([[[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[1,2,3],[4,5,6]]]])
print(arr1)
print(arr1.ndim)
print(arr1.shape)          
print(arr1.size)

[[[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]

  [[ 1  2  3]
   [ 4  5  6]]]]
4
(1, 3, 2, 3)
18


In [56]:
arr1=np.array([[[[1,2,3],[5,6,7],[4,5,6]],[[7,8,9],[5,6,7],[10,11,12]],[[1,2,3],[5,6,7],[4,5,6]]]])
print(arr1)
print(arr1.ndim)
print(arr1.shape)          
print(arr1.size)

[[[[ 1  2  3]
   [ 5  6  7]
   [ 4  5  6]]

  [[ 7  8  9]
   [ 5  6  7]
   [10 11 12]]

  [[ 1  2  3]
   [ 5  6  7]
   [ 4  5  6]]]]
4
(1, 3, 3, 3)
27


In [65]:
mat=[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]
b=np.array(mat)
print(b)
print(b.ndim)
print(b.shape)
print(b[0])
print(b[0,1:2])
print(b[1,2:4])
print(b[1,4:])
print(b[0:2,1:])    #rows,columns

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
2
(3, 5)
[1 2 3 4 5]
[2]
[8 9]
[10]
[[ 2  3  4  5]
 [ 7  8  9 10]]


BUILT - IN FUNCTIONS
RESHAPE 

-- Changing shape of an array

-- converting 1D-2D-3D

In [79]:
a1=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18])
a1.reshape(2,9)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18]])

In [80]:
a1.reshape(9,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18]])

In [81]:
a1.reshape(3,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18]])

In [82]:
a1.reshape(6,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [83]:
a1.reshape(1,18)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18]])

In [84]:
a1.reshape(5,3)

ValueError: cannot reshape array of size 18 into shape (5,3)

In [85]:
a1.reshape(2,3,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [87]:
a1.reshape(3,2,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [88]:
a1.reshape(3,3,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]]])

In [89]:
a1.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18])

ARANGE

-- Creating sequence with step values.

-- returns evenly spaced values within the interval.

In [12]:
np.arange(25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [13]:
np.arange(5,18)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17])

In [14]:
np.arange(0,20,2.3)

array([ 0. ,  2.3,  4.6,  6.9,  9.2, 11.5, 13.8, 16.1, 18.4])

In [15]:
#start - 23
#end - 678
#step - 55.5
np.arange(23,678,55.5)

array([ 23. ,  78.5, 134. , 189.5, 245. , 300.5, 356. , 411.5, 467. ,
       522.5, 578. , 633.5])

In [91]:
np.arange(2,30,5)

array([ 2,  7, 12, 17, 22, 27])

In [ ]:
# Creating the arrays filled with Zero's and One's

In [93]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [95]:
np.zeros([2,3,2])

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [96]:
np.zeros([3,5,3])

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [97]:
np.ones([3,5,4])

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

EYE 

-- identity matrix

-- It generates an identity matrix, which is square matrix with 1's in diagonal and 0's everwhere else

In [103]:
np.eye(4,dtype=int)      #eye diagonal it should be one

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [105]:
np.eye(4,dtype=complex)

array([[1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j]])

In [25]:
a = [10,20,30,40,50]
b = 100

In [26]:
result = []

In [27]:
for x in a:
    result.append(x+b)
print(result)

[110, 120, 130, 140, 150]


In [28]:
a_1 = np.array([10,20,30,40,50])
b_1 = 100

In [29]:
print(a_1+b_1)

[110 120 130 140 150]


LINSPACE

-- Generating evenly spaced values
-- Difference should be (end index-start index/step index-1)

In [116]:
np.linspace(0,25,retstep=True)    #25-0/50-1   end index-start index/step index-1

(array([ 0.        ,  0.51020408,  1.02040816,  1.53061224,  2.04081633,
         2.55102041,  3.06122449,  3.57142857,  4.08163265,  4.59183673,
         5.10204082,  5.6122449 ,  6.12244898,  6.63265306,  7.14285714,
         7.65306122,  8.16326531,  8.67346939,  9.18367347,  9.69387755,
        10.20408163, 10.71428571, 11.2244898 , 11.73469388, 12.24489796,
        12.75510204, 13.26530612, 13.7755102 , 14.28571429, 14.79591837,
        15.30612245, 15.81632653, 16.32653061, 16.83673469, 17.34693878,
        17.85714286, 18.36734694, 18.87755102, 19.3877551 , 19.89795918,
        20.40816327, 20.91836735, 21.42857143, 21.93877551, 22.44897959,
        22.95918367, 23.46938776, 23.97959184, 24.48979592, 25.        ]),
 np.float64(0.5102040816326531))

In [109]:
24.48979592+0.51020408

25.0

In [110]:
25/49

0.5102040816326531

17/9

In [112]:
np.linspace(3,20,10,retstep=True)        #20-3/10-1=1.88888888888

(array([ 3.        ,  4.88888889,  6.77777778,  8.66666667, 10.55555556,
        12.44444444, 14.33333333, 16.22222222, 18.11111111, 20.        ]),
 np.float64(1.8888888888888888))

In [114]:
np.linspace(3,20,10,retstep=False)

array([ 3.        ,  4.88888889,  6.77777778,  8.66666667, 10.55555556,
       12.44444444, 14.33333333, 16.22222222, 18.11111111, 20.        ])

In [111]:
17/9

1.8888888888888888

In [117]:
np.linspace(3,10,2,retstep=False)

array([ 3., 10.])

In [118]:
np.linspace(3,10,2,retstep=True)

(array([ 3., 10.]), np.float64(7.0))

In [75]:
np.random.rand(10)

array([0.84653071, 0.37071306, 0.93338144, 0.09903343, 0.38275534,
       0.51335994, 0.78432745, 0.44015373, 0.51083559, 0.45030733])

In [81]:
np.random.randn(10)

array([-0.3251579 ,  2.88211284,  0.00484493,  0.49198712, -1.28656935,
       -1.00927844,  0.19583655,  1.34828367,  0.4407646 ,  0.48438423])

In [74]:
np.random.randint(1,12)

3

In [73]:
np.random.randint(12)

10

In [90]:
a2=np.random.randint(10)
print(a2)
print(np.mean(a2))
print(np.median(a2))
print(np.std(a2))

1
1.0
1.0
0.0


In [92]:
a1=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18])
print(a1)
print(np.mean(a1))
print(np.median(a1))
print(np.std(a1))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
9.5
9.5
5.188127472091127


In [95]:
a3=np.random.randint(50,100,20)
a3

array([88, 90, 84, 85, 81, 69, 59, 56, 94, 61, 60, 84, 50, 64, 87, 89, 73,
       88, 90, 97], dtype=int32)

In [96]:
a3.max()  #it returns max element

np.int32(97)

In [97]:
print(a3.max())

97


In [99]:
a3.min()

np.int32(50)

In [98]:
print(a3.min())

50


In [100]:
a3.argmax()      #it returns max element index position

np.int64(19)

In [101]:
a3.argmin()

np.int64(12)

In [102]:
a=np.array([1,2,1010,4,108,18,71,610])
a

array([   1,    2, 1010,    4,  108,   18,   71,  610])

In [103]:
a[a<100]       #it gives array elements which are less than 100

array([ 1,  2,  4, 18, 71])

In [105]:
print(np.where(a>100))     

(array([2, 4, 7]),)


In [106]:
print(np.where(a>601))

(array([2, 7]),)


In [107]:
b=np.array([True,False,False,True,False])
np.where(b)

(array([0, 3]),)

In [109]:
b=np.array([0,1,0,1,1])
np.where(b)

(array([1, 3, 4]),)

In [111]:
a=np.arange(12).reshape(4,3)
b=np.arange(3)
print(a)
print(b)
print(a+b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[0 1 2]
[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]
 [ 9 11 13]]


In [112]:
a=np.arange(12).reshape(4,3)
b=np.arange(3,1)
print(a)
print(b)
print(a+b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[]


ValueError: operands could not be broadcast together with shapes (4,3) (0,) 

In [113]:
a=np.arange(12).reshape(3,4)
b=np.arange(3)
print(a)
print(b)
print(a+b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0 1 2]


ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [114]:
a=np.arange(3).reshape(1,3)
b=np.arange(3).reshape(3,1)
print(a)
print(b)
print(a+b)
#(1,3)  (3,1)
#(3,3)  (3,3)

[[0 1 2]]
[[0]
 [1]
 [2]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [116]:
a=np.arange(4).reshape(4,1)
b=np.arange(3).reshape(1,3)
print(a)
print(b)
print(a+b)

[[0]
 [1]
 [2]
 [3]]
[[0 1 2]]
[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]]


In [117]:
a=np.arange(12).reshape(3,4)
b=np.arange(12).reshape(4,3)
print(a)
print(b)
print(a+b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


ValueError: operands could not be broadcast together with shapes (3,4) (4,3) 

In [119]:
a=np.arange(16).reshape(4,4)
b=np.arange(4).reshape(4,1)
print(a)
print(b)
print(a+b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[0]
 [1]
 [2]
 [3]]
[[ 0  1  2  3]
 [ 5  6  7  8]
 [10 11 12 13]
 [15 16 17 18]]


In [121]:
a = np.array([1])
# shape -> (1,1)
b = np.arange(4).reshape(2,2)
# shape -> (2,2)

print(a)
print(b)

print(a*b)

[1]
[[0 1]
 [2 3]]
[[0 1]
 [2 3]]


In [2]:
arr=np.arange(100).reshape(10,10)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [17]:
fan_arr = np.arange(100).reshape(10,10)
fan_arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [18]:
fan_arr[[6,3,9,1]]  # fancy indexing on rows

array([[60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [19]:
fan_arr[:,[2,5,7]]

array([[ 2,  5,  7],
       [12, 15, 17],
       [22, 25, 27],
       [32, 35, 37],
       [42, 45, 47],
       [52, 55, 57],
       [62, 65, 67],
       [72, 75, 77],
       [82, 85, 87],
       [92, 95, 97]])